name: CI
on:
  push:
    # This private feature branch has a focused Windows package workflow.
    branches-ignore: [feature/usable-desktop-window-layout]
  pull_request:
#  schedule:
#    - cron: '0 0-23/4 * * *'
permissions:
  contents: read
jobs:
  windows:
    name: Windows x64
    runs-on: windows-latest
    env:
      CONFIGURATION: Debug
      PLATFORM: x64
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VCPKG_FEATURE_FLAGS: dependencygraph
      VCPKG_DEFAULT_TRIPLET: x64-windows
      VCPKG_INSTALLED_DIR: ${{ github.workspace }}/vcpkg_installed
      VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}/vcpkg_cache,readwrite
      VCPKG_OVERLAY_PORTS: ${{ github.workspace }}/.github/vcpkg-ports
      GIT_VCPKG_COMMIT: ef7dbf94b9198bc58f45951adcf1f041fcbc5ea0
    permissions:
      contents: write # For dependencygraph
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install vcpkg
        uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
          vcpkgGitCommitId: ${{ env.GIT_VCPKG_COMMIT }}
      - name: Integrate vcpkg
        run: |
          ${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}/vcpkg integrate install
      - name: Restore vcpkg cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}/vcpkg_cache
          key: vcpkg-${{ env.GIT_VCPKG_COMMIT }}-x64-windows-${{ hashFiles('vcpkg.json', 'vcpkg_installed/compiler-file-hash-cache.json', 'vcpkg_installed/status') }}
          restore-keys: vcpkg-${{ env.GIT_VCPKG_COMMIT }}-x64-windows-
      - name: Build create_project
        run: |
          cd devtools/create_project/cmake
          cmake .
          cmake --build . -j 2
          ls
          cd ../../../
      - name: Call create_project
        run: |
          mkdir build-scummvm
          cd build-scummvm
          ../devtools/create_project/cmake/Debug/create_project.exe .. --msvc --vcpkg --enable-all-engines --enable-discord --enable-faad --enable-gif --enable-mikmod --enable-mpeg2 --enable-vpx
          ls
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Install vcpkg packages
        run: |
          vcpkg install
      - name: Save vcpkg cache
        uses: actions/cache/save@v4
        with:
          path: ${{ github.workspace }}/vcpkg_cache
          key: vcpkg-${{ env.GIT_VCPKG_COMMIT }}-x64-windows-${{ hashFiles('vcpkg.json', 'vcpkg_installed/compiler-file-hash-cache.json', 'vcpkg_installed/status') }}
      - name: Build scummvm
        run: |
          cd build-scummvm
          ls
          msbuild scummvm.sln /m /p:VcpkgEnableManifest=true /p:BuildInParallel=true /p:Configuration=${{ env.CONFIGURATION }} /p:PreferredToolArchitecture=x64 /p:Platform=x64 /v:minimal
